In [3]:
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import chardet
import plotly_express as px

""" Emissions"""
dataset_path_emi = '/Users/stijnbrons/Documents/GitHub/Project-TIL6022/Data/Emissies_naar_lucht__Nederland_totaal_04102024_195121.csv'
with open(dataset_path_mat, 'rb') as rawdata:

    result = chardet.detect(rawdata.read(100000))
    
result

{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}

In [5]:
df_emi = pd.read_csv(dataset_path_mat,delimiter=';',encoding='UTF-8-SIG')
df_emi

,Emissiebronnen,Emissies naar lucht,Perioden,Emissies naar lucht (mln kg)
0,Vervoer,Kooldioxide (CO2),1990,30000.0
1,Vervoer,Kooldioxide (CO2),1995,31800.0
2,Vervoer,Kooldioxide (CO2),2000,35600.0
3,Vervoer,Kooldioxide (CO2),2001,36100.0
4,Vervoer,Kooldioxide (CO2),2002,36600.0
...,...,...,...,...
2075,Railverkeer; totaal,Koolmonoxide (CO),2019,0.2
2076,Railverkeer; totaal,Koolmonoxide (CO),2020,0.2
2077,Railverkeer; totaal,Koolmonoxide (CO),2021,0.2
2078,Railverkeer; totaal,Koolmonoxide (CO),2022,0.2
2079,Railverkeer; totaal,Koolmonoxide (CO),2023*,0.3

In [ ]:
px.line(x=Perioden,
        y=)